# Generated by Django 3.1 on 2020-08-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_usa',
            new_name='fess_in_usa',
        ),
    ]
