# Generated by Django 3.1 on 2020-08-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200818_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_usa',
            new_name='fees_in_usa',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_world',
            new_name='fees_in_world',
        ),
    ]
